/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OtherPageRouteImport } from './routes/other-page'
import { Route as IndexRouteImport } from './routes/index'

const OtherPageRoute = OtherPageRouteImport.update({
  id: '/other-page',
  path: '/other-page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/other-page': typeof OtherPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/other-page': typeof OtherPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/other-page': typeof OtherPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/other-page'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/other-page'
  id: '__root__' | '/' | '/other-page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OtherPageRoute: typeof OtherPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/other-page': {
      id: '/other-page'
      path: '/other-page'
      fullPath: '/other-page'
      preLoaderRoute: typeof OtherPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OtherPageRoute: OtherPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
